package com.przemo.tradex.data;
// Generated 2014-02-13 15:12:34 by Hibernate Tools 3.2.1.GA



/**
 * AccountTypes generated by hbm2java
 */
public class AccountTypes  implements java.io.Serializable {


     private int id;
     private String accountName;
     private String accountDescription;

    public AccountTypes() {
    }

	
    public AccountTypes(int id, String accountName) {
        this.id = id;
        this.accountName = accountName;
    }
    public AccountTypes(int id, String accountName, String accountDescription) {
       this.id = id;
       this.accountName = accountName;
       this.accountDescription = accountDescription;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getAccountName() {
        return this.accountName;
    }
    
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }
    public String getAccountDescription() {
        return this.accountDescription;
    }
    
    public void setAccountDescription(String accountDescription) {
        this.accountDescription = accountDescription;
    }




}


