package com.przemo.tradex.data;
// Generated 2014-02-13 15:12:34 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Accounts generated by hbm2java
 */
public class Accounts  implements java.io.Serializable {


     private int id;
     private Users users;
     private int accountNumber;
     private double balance;
     private boolean active;
     private Set accountsHistories = new HashSet(0);

    public Accounts() {
    }

	
    public Accounts(int id, Users users, int accountNumber, double balance, boolean active) {
        this.id = id;
        this.users = users;
        this.accountNumber = accountNumber;
        this.balance = balance;
        this.active = active;
    }
    public Accounts(int id, Users users, int accountNumber, double balance, boolean active, Set accountsHistories) {
       this.id = id;
       this.users = users;
       this.accountNumber = accountNumber;
       this.balance = balance;
       this.active = active;
       this.accountsHistories = accountsHistories;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public int getAccountNumber() {
        return this.accountNumber;
    }
    
    public void setAccountNumber(int accountNumber) {
        this.accountNumber = accountNumber;
    }
    public double getBalance() {
        return this.balance;
    }
    
    public void setBalance(double balance) {
        this.balance = balance;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Set getAccountsHistories() {
        return this.accountsHistories;
    }
    
    public void setAccountsHistories(Set accountsHistories) {
        this.accountsHistories = accountsHistories;
    }




}


