package com.przemo.tradex.data;
// Generated 2014-02-13 15:12:34 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Equities generated by hbm2java
 */
public class Equities  implements java.io.Serializable {


     private int id;
     private EquitiesTypes equitiesTypes;
     private String equitySymbol;
     private double bidPrice;
     private double askPrice;
     private String description;
     private Set equitiesPriceHistories = new HashSet(0);
     private Set orderses = new HashSet(0);
     private Set transactionses = new HashSet(0);

    public Equities() {
    }

	
    public Equities(int id, String equitySymbol, double bidPrice, double askPrice) {
        this.id = id;
        this.equitySymbol = equitySymbol;
        this.bidPrice = bidPrice;
        this.askPrice = askPrice;
    }
    public Equities(int id, EquitiesTypes equitiesTypes, String equitySymbol, double bidPrice, double askPrice, String description, Set equitiesPriceHistories, Set orderses, Set transactionses) {
       this.id = id;
       this.equitiesTypes = equitiesTypes;
       this.equitySymbol = equitySymbol;
       this.bidPrice = bidPrice;
       this.askPrice = askPrice;
       this.description = description;
       this.equitiesPriceHistories = equitiesPriceHistories;
       this.orderses = orderses;
       this.transactionses = transactionses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public EquitiesTypes getEquitiesTypes() {
        return this.equitiesTypes;
    }
    
    public void setEquitiesTypes(EquitiesTypes equitiesTypes) {
        this.equitiesTypes = equitiesTypes;
    }
    public String getEquitySymbol() {
        return this.equitySymbol;
    }
    
    public void setEquitySymbol(String equitySymbol) {
        this.equitySymbol = equitySymbol;
    }
    public double getBidPrice() {
        return this.bidPrice;
    }
    
    public void setBidPrice(double bidPrice) {
        this.bidPrice = bidPrice;
    }
    public double getAskPrice() {
        return this.askPrice;
    }
    
    public void setAskPrice(double askPrice) {
        this.askPrice = askPrice;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getEquitiesPriceHistories() {
        return this.equitiesPriceHistories;
    }
    
    public void setEquitiesPriceHistories(Set equitiesPriceHistories) {
        this.equitiesPriceHistories = equitiesPriceHistories;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }
    public Set getTransactionses() {
        return this.transactionses;
    }
    
    public void setTransactionses(Set transactionses) {
        this.transactionses = transactionses;
    }




}


