package com.przemo.tradex.data;
// Generated 2014-02-13 15:12:34 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * EquitiesTypes generated by hbm2java
 */
public class EquitiesTypes  implements java.io.Serializable {


     private int id;
     private String typeName;
     private String description;
     private Set equitieses = new HashSet(0);

    public EquitiesTypes() {
    }

	
    public EquitiesTypes(int id) {
        this.id = id;
    }
    public EquitiesTypes(int id, String typeName, String description, Set equitieses) {
       this.id = id;
       this.typeName = typeName;
       this.description = description;
       this.equitieses = equitieses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getEquitieses() {
        return this.equitieses;
    }
    
    public void setEquitieses(Set equitieses) {
        this.equitieses = equitieses;
    }




}


