package com.przemo.tradex.data;
// Generated 2014-02-13 15:12:34 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * News generated by hbm2java
 */
public class News  implements java.io.Serializable {


     private int id;
     private Date issueDate;
     private String title;
     private String contents;

    public News() {
    }

	
    public News(int id, Date issueDate, String title) {
        this.id = id;
        this.issueDate = issueDate;
        this.title = title;
    }
    public News(int id, Date issueDate, String title, String contents) {
       this.id = id;
       this.issueDate = issueDate;
       this.title = title;
       this.contents = contents;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getIssueDate() {
        return this.issueDate;
    }
    
    public void setIssueDate(Date issueDate) {
        this.issueDate = issueDate;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getContents() {
        return this.contents;
    }
    
    public void setContents(String contents) {
        this.contents = contents;
    }




}


