package com.przemo.tradex.data;
// Generated 2014-02-13 15:12:34 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * OrderTypes generated by hbm2java
 */
public class OrderTypes  implements java.io.Serializable {


     private int id;
     private String orderType;
     private String description;
     private Set orderses = new HashSet(0);

    public OrderTypes() {
    }

	
    public OrderTypes(int id, String orderType, String description) {
        this.id = id;
        this.orderType = orderType;
        this.description = description;
    }
    public OrderTypes(int id, String orderType, String description, Set orderses) {
       this.id = id;
       this.orderType = orderType;
       this.description = description;
       this.orderses = orderses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getOrderType() {
        return this.orderType;
    }
    
    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


