package com.przemo.tradex.data;
// Generated 2014-02-13 15:12:34 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private long id;
     private OrderTypes orderTypes;
     private Equities equities;
     private Users users;
     private double quantity;
     private double initialQuantity;
     private Date validThru;
     private double minQuantity;
     private Set transactionsesForSellerOrderId = new HashSet(0);
     private Set transactionsesForBuyerOrderId = new HashSet(0);

    public Orders() {
    }

	
    public Orders(long id, OrderTypes orderTypes, Equities equities, Users users, double quantity, double initialQuantity, double minQuantity) {
        this.id = id;
        this.orderTypes = orderTypes;
        this.equities = equities;
        this.users = users;
        this.quantity = quantity;
        this.initialQuantity = initialQuantity;
        this.minQuantity = minQuantity;
    }
    public Orders(long id, OrderTypes orderTypes, Equities equities, Users users, double quantity, double initialQuantity, Date validThru, double minQuantity, Set transactionsesForSellerOrderId, Set transactionsesForBuyerOrderId) {
       this.id = id;
       this.orderTypes = orderTypes;
       this.equities = equities;
       this.users = users;
       this.quantity = quantity;
       this.initialQuantity = initialQuantity;
       this.validThru = validThru;
       this.minQuantity = minQuantity;
       this.transactionsesForSellerOrderId = transactionsesForSellerOrderId;
       this.transactionsesForBuyerOrderId = transactionsesForBuyerOrderId;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public OrderTypes getOrderTypes() {
        return this.orderTypes;
    }
    
    public void setOrderTypes(OrderTypes orderTypes) {
        this.orderTypes = orderTypes;
    }
    public Equities getEquities() {
        return this.equities;
    }
    
    public void setEquities(Equities equities) {
        this.equities = equities;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public double getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(double quantity) {
        this.quantity = quantity;
    }
    public double getInitialQuantity() {
        return this.initialQuantity;
    }
    
    public void setInitialQuantity(double initialQuantity) {
        this.initialQuantity = initialQuantity;
    }
    public Date getValidThru() {
        return this.validThru;
    }
    
    public void setValidThru(Date validThru) {
        this.validThru = validThru;
    }
    public double getMinQuantity() {
        return this.minQuantity;
    }
    
    public void setMinQuantity(double minQuantity) {
        this.minQuantity = minQuantity;
    }
    public Set getTransactionsesForSellerOrderId() {
        return this.transactionsesForSellerOrderId;
    }
    
    public void setTransactionsesForSellerOrderId(Set transactionsesForSellerOrderId) {
        this.transactionsesForSellerOrderId = transactionsesForSellerOrderId;
    }
    public Set getTransactionsesForBuyerOrderId() {
        return this.transactionsesForBuyerOrderId;
    }
    
    public void setTransactionsesForBuyerOrderId(Set transactionsesForBuyerOrderId) {
        this.transactionsesForBuyerOrderId = transactionsesForBuyerOrderId;
    }




}


