package com.przemo.tradex.data;
// Generated 2014-02-13 15:12:34 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transactions generated by hbm2java
 */
public class Transactions  implements java.io.Serializable {


     private long id;
     private Orders ordersByBuyerOrderId;
     private Equities equities;
     private Orders ordersBySellerOrderId;
     private double quantity;
     private double price;
     private Date transactionDate;
     private Set accountsHistories = new HashSet(0);

    public Transactions() {
    }

	
    public Transactions(long id, Orders ordersByBuyerOrderId, Equities equities, Orders ordersBySellerOrderId, double quantity, double price, Date transactionDate) {
        this.id = id;
        this.ordersByBuyerOrderId = ordersByBuyerOrderId;
        this.equities = equities;
        this.ordersBySellerOrderId = ordersBySellerOrderId;
        this.quantity = quantity;
        this.price = price;
        this.transactionDate = transactionDate;
    }
    public Transactions(long id, Orders ordersByBuyerOrderId, Equities equities, Orders ordersBySellerOrderId, double quantity, double price, Date transactionDate, Set accountsHistories) {
       this.id = id;
       this.ordersByBuyerOrderId = ordersByBuyerOrderId;
       this.equities = equities;
       this.ordersBySellerOrderId = ordersBySellerOrderId;
       this.quantity = quantity;
       this.price = price;
       this.transactionDate = transactionDate;
       this.accountsHistories = accountsHistories;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Orders getOrdersByBuyerOrderId() {
        return this.ordersByBuyerOrderId;
    }
    
    public void setOrdersByBuyerOrderId(Orders ordersByBuyerOrderId) {
        this.ordersByBuyerOrderId = ordersByBuyerOrderId;
    }
    public Equities getEquities() {
        return this.equities;
    }
    
    public void setEquities(Equities equities) {
        this.equities = equities;
    }
    public Orders getOrdersBySellerOrderId() {
        return this.ordersBySellerOrderId;
    }
    
    public void setOrdersBySellerOrderId(Orders ordersBySellerOrderId) {
        this.ordersBySellerOrderId = ordersBySellerOrderId;
    }
    public double getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(double quantity) {
        this.quantity = quantity;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }
    public Set getAccountsHistories() {
        return this.accountsHistories;
    }
    
    public void setAccountsHistories(Set accountsHistories) {
        this.accountsHistories = accountsHistories;
    }




}


