package com.przemo.tradex.data;
// Generated 2014-02-13 15:12:34 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * UserSessions generated by hbm2java
 */
public class UserSessions  implements java.io.Serializable {


     private long id;
     private Users users;
     private Date loginTime;
     private Date logoutTime;
     private String sessionKey;
     private Date expiryDate;
     private String loginIp;

    public UserSessions() {
    }

	
    public UserSessions(long id, Users users, Date loginTime, String sessionKey, Date expiryDate) {
        this.id = id;
        this.users = users;
        this.loginTime = loginTime;
        this.sessionKey = sessionKey;
        this.expiryDate = expiryDate;
    }
    public UserSessions(long id, Users users, Date loginTime, Date logoutTime, String sessionKey, Date expiryDate, String loginIp) {
       this.id = id;
       this.users = users;
       this.loginTime = loginTime;
       this.logoutTime = logoutTime;
       this.sessionKey = sessionKey;
       this.expiryDate = expiryDate;
       this.loginIp = loginIp;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getLoginTime() {
        return this.loginTime;
    }
    
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }
    public Date getLogoutTime() {
        return this.logoutTime;
    }
    
    public void setLogoutTime(Date logoutTime) {
        this.logoutTime = logoutTime;
    }
    public String getSessionKey() {
        return this.sessionKey;
    }
    
    public void setSessionKey(String sessionKey) {
        this.sessionKey = sessionKey;
    }
    public Date getExpiryDate() {
        return this.expiryDate;
    }
    
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }
    public String getLoginIp() {
        return this.loginIp;
    }
    
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }




}


