package com.przemo.tradex.data;
// Generated 2014-02-13 15:12:34 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int id;
     private String username;
     private String password;
     private String lastIpLogin;
     private Date lastLogin;
     private Set accountses = new HashSet(0);
     private Set orderses = new HashSet(0);
     private Set userSessionses = new HashSet(0);

    public Users() {
    }

	
    public Users(int id, String username, String password, Date lastLogin) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.lastLogin = lastLogin;
    }
    public Users(int id, String username, String password, String lastIpLogin, Date lastLogin, Set accountses, Set orderses, Set userSessionses) {
       this.id = id;
       this.username = username;
       this.password = password;
       this.lastIpLogin = lastIpLogin;
       this.lastLogin = lastLogin;
       this.accountses = accountses;
       this.orderses = orderses;
       this.userSessionses = userSessionses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getLastIpLogin() {
        return this.lastIpLogin;
    }
    
    public void setLastIpLogin(String lastIpLogin) {
        this.lastIpLogin = lastIpLogin;
    }
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
    public Set getAccountses() {
        return this.accountses;
    }
    
    public void setAccountses(Set accountses) {
        this.accountses = accountses;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }
    public Set getUserSessionses() {
        return this.userSessionses;
    }
    
    public void setUserSessionses(Set userSessionses) {
        this.userSessionses = userSessionses;
    }




}


